substitutions:
  name: lohas-rgbww-b702d5
  friendly_name: "Main Hallway Lamp 2"

packages:
  esphome.lohas-rgbww-template: github://bradsjm/esphome/templates/lohas-rgbww-template.yaml

esphome:
  name_add_mac_suffix: false

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
