substitutions:
  name: lohas-rgbww-c34e40
  friendly_name: "Main Hallway Lamp 3"
  comment: "Main Hallway Lamp 3"

packages:
  esphome.lohas-rgbww-template: github://bradsjm/esphome/templates/lohas-rgbww-template.yaml

esphome:
  name_add_mac_suffix: false

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
