substitutions:
  name: lohas-rgbww-bf30af
  friendly_name: "Living Room Table Lamp"

packages:
  esphome.lohas-rgbww-template: github://bradsjm/esphome/templates/lohas-rgbww-template.yaml

esphome:
  name_add_mac_suffix: false

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
