substitutions:
  name: "lohas-rgbww"
  friendly_name: "Lohas Bulb"
  comment: "Lohas Bulb"
  disable_entities: "true"

# This should point to the public location of this yaml file.
dashboard_import:
  package_import_url: github://bradsjm/esphome/templates/lohas-rgbww-template.yaml

esphome:
  name: $name
  name_add_mac_suffix: true
  comment: $comment
  project:
    name: esphome.lohas-rgbww-template
    version: "1.0"

esp8266:
  board: esp01_1m
  restore_from_flash: true

logger:                  # To be able to get logs from the device via serial and api
  level: DEBUG
  baud_rate: 0           # Disable UART logging

api:                     # API is a requirement of the dashboard import
  reboot_timeout: 0s

ota:                     # OTA is required for Over-the-Air updating
  on_error:
    then:
      - button.press: restart_button

wifi:                    # Set up a wifi access point using the device name above
  ap: {}
  output_power: 17

captive_portal:

web_server:              # web server allows access to device with a web browser

time:                    # sntp time client for daily power consumption
  - platform: sntp
    timezone: "America/New_York"

button:
  - platform: restart
    id: restart_button
    name: "${friendly_name} Restart"
    entity_category: diagnostic
    disabled_by_default: true

sensor:
  - platform: uptime
    name: "${friendly_name} Uptime"
    update_interval: 60s
    entity_category: diagnostic
    disabled_by_default: true
    unit_of_measurement: m
    filters:
      - lambda: return x / 60.0;

  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 60s
    entity_category: diagnostic
    disabled_by_default: true
    filters:
      - delta: 5

  - platform: template
    id: power
    name: "${friendly_name} Power Consumption"
    unit_of_measurement: W
    accuracy_decimals: 1
    update_interval: 60s
    device_class: power
    state_class: measurement
    icon: mdi:flash

  - platform: total_daily_energy
    name: "${friendly_name} Total Daily Energy"
    power_id: power
    filters:
        # Multiplication factor from W to kW is 0.001
        - multiply: 0.001
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    icon: mdi:flash

output:                                 # PWM outputs for each LED channel
  - platform: esp8266_pwm
    pin: GPIO5
    id: pwm_red
  - platform: esp8266_pwm
    pin: GPIO4
    id: pwm_green
  - platform: esp8266_pwm
    pin: GPIO13
    id: pwm_blue
  - platform: esp8266_pwm
    pin: GPIO14
    id: pwm_cw
  - platform: esp8266_pwm
    pin: GPIO12
    id: pwm_ww

light:
  - platform: rgbww
    id: lightbulb
    default_transition_length: 1000ms
    name: $friendly_name
    red: pwm_red
    green: pwm_green
    blue: pwm_blue
    warm_white: pwm_ww
    cold_white: pwm_cw
    cold_white_color_temperature: 6000 K
    warm_white_color_temperature: 2700 K
    color_interlock: true
    constant_brightness: true
    on_turn_on:
      - sensor.template.publish:
          id: power
          state: !lambda 'return 6.0 * id(lightbulb).remote_values.get_brightness();'
    on_state:
      - sensor.template.publish:
          id: power
          state: !lambda 'return 6.0 * id(lightbulb).remote_values.get_brightness();'
    on_turn_off:
      - sensor.template.publish:
          id: power
          state: 0.2
    effects:
      - pulse:
          name: "Slow Pulse"
          transition_length: 1s
          update_interval: 2s
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.5s
          update_interval: 0.5s
      - lambda:
          name: DDP
          update_interval: 0s
          lambda: |-
            static float scaled_r = 0.0;
            static float scaled_g = 0.0;
            static float scaled_b = 0.0;
            static std::unique_ptr<WiFiUDP> udp_;
          
            if (!udp_) {
              udp_ = make_unique<WiFiUDP>();
              if (!udp_->begin(4048)) {   // always listen on DDP port
                return;
              }
            }
            
            std::vector<uint8_t> payload;
            while (uint16_t packet_size = udp_->parsePacket()) {
              payload.resize(packet_size);
              if (!udp_->read(&payload[0], payload.size())) {
                continue;
              }
            }
        
            if (payload.size() < 2) {
              return;
            }
  
            float r = (float)payload[10]/255.0f;
            float g = (float)payload[11]/255.0f;
            float b = (float)payload[12]/255.0f;
            
            float m = 0.0f;
            if ( (r>=g) && (r>=b) ) { m = r; }
            else if ( g >= b )      { m = g; }
            else                    { m = b; }
            
            if (m != 0.0f) {
              scaled_r = r/m;
              scaled_g = g/m;
              scaled_b = b/m;
            } else {
              scaled_r = 0.0f;
              scaled_g = 0.0f;
              scaled_b = 0.0f;
            }
            auto call = id(lightbulb).turn_on();
            call.set_transition_length(0);
            call.set_brightness(m); 
            call.set_color_mode(ColorMode::RGB);
            call.set_rgb(scaled_r, scaled_g, scaled_b);
            call.set_publish(false);
            call.set_save(false);
            call.perform();
